### ISSUE TITLE
Failed to launch 

### ISSUE THREAD

**Issue by heret0x0** [sufone/qawl-svelte#83]
on fedora 37
official appimage
v0.7
running the package shows a notification about new release which refers to the 0.8 tag that doesnt contain any pre built packages to download
and while trying to get that update doesnt make the app processes to be killed it keeps its processes alive on the background
also using the "Update Later" option kills the processes immediately 
and in both cases the app doesnt display the ui

may allah reward you all.

**Comment by mr-islam** [comment]
Wa iyyakum 💚

Thank you so much for reporting this issue! I have removed the 0.8 tag release - could you please try again and let me know if it works now?

**Comment by heret0x0** [comment]
thanks its working now
although just running the appimage causes that common electron issue for me:
`[21736:1202/020355.871798:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)`
which i think is what made the app crashes after clicking on **"Update Later"** before
idk if its a driver issue maybe but ig that its from my side
i managed to fix that by just running it on terminal with `--in-process-gpu`, `--no-sandbox` or `--disable-gpu-sandbox` options
Except that it works just fine
jazakallah khair!

**Comment by mr-islam** [comment]
Alhamdulillah

I think that bug has to do with Electron itself, there were a lot of bugs specially relating to Wayland and nvidia graphics. Qawl still uses an older Electron version.

InshaAllah the plan is to re-write Qawl in [Tauri](https://tauri.app/) to make it perform better and work on mobile too
