### ISSUE TITLE
What font was used in the Qur'an app?

### ISSUE THREAD

**Issue by digitaldrreamer** [sufone/qawl-svelte#85]
Assalamu aleikum wa rahmatullahi wa barakaatuhu brother.
Just wanted to know what font was used in the Mushaf images. Help will be greatly appreciated. Jazakumullahu Khairan

**Comment by mr-islam** [comment]
Wa alaykum as salam wa rahmatullahi wa barakatuhu dear brother

Qawl is not using a font, rather they're images directly from the Mushaf scan, I got them from [here](https://qurancomplex.gov.sa/en/kfgqpc-quran-hafs/).

If you would like the fonts, you can find them [here](https://github.com/mustafa0x/qpc-fonts).

**Comment by Libax470** [comment]
Assalamu Alaikum Wa Rahmatullahi Wa Barakatuh my brother @mr-islam, 
Is it possible to get [this Mushaf images](https://raw.githubusercontent.com/sufone/qawl/master/public/mushaf/1.png) as a high quality images or svg. I am trying to use it for a youtube video.
JazakAllahu Khairan.

**Comment by mr-islam** [comment]
Wa alaykum as salam wa rahmatullahi wa barakatuhu dear brother @Libax470 

All the images are available [here](https://github.com/sufone/qawl/tree/master/public/mushaf)

Let me know if I can help with anything else, and I'll convert this to a discussion
